export async function buildHypeframesAgentPrompt(_projectPath: string): Promise<string> {
  return [
    "Refine the generated Qivance HypeFrames HTML composition using repo-scoped HyperFrames skills.",
    "",
    "Use the repo-scoped HyperFrames skills in hypeframes/.agents/skills when relevant.",
    "",
    "Input files:",
    "- data/timing/beats.locked.json",
    "- data/timing/section_map.json",
    "- data/storyboard/scene_plan.json",
    "- data/storyboard/caption_plan.json",
    "- data/storyboard/visual_plan.json",
    "- hypeframes/src/index.html",
    "- hypeframes/src/styles.css",
    "- hypeframes/src/main.js",
    "- hypeframes/src/config.json",
    "- hypeframes/render_targets/render_targets.json",
    "",
    "Allowed modifications:",
    "- hypeframes/**",
    "- qa/hypeframes/hypeframes_revision_notes.md",
    "- logs/codex/**",
    "",
    "Forbidden modifications:",
    "- audio/**",
    "- data/timing/**",
    "- data/lyrics/**",
    "- project_manifest.json",
    "- workflow_snapshot.json",
    "- dist/**",
    "- qa/music/**",
    "- qa/timing/**",
    "",
    "Do not use external URLs, random runtime dependencies, audio edits, timing truth edits, forged QA passes, final dist renders, or project manifest rewrites.",
    "Write concise revision notes only when useful. Do not print long non-structured explanations.",
    "",
  ].join("\n");
}
